# Generated by Django 5.2.6 on 2025-10-01 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('visit', 'Visit Ad'), ('short', 'Short Link'), ('video', 'Video Ad'), ('offerwalla', 'Offerwalls'), ('cpi', 'CPI/CPS/CPL')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('duration', models.PositiveIntegerField(help_text='Ad Duration in Seconds')),
                ('max_show', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('ad_type', models.CharField(choices=[('url', 'URL/LINK'), ('banner', 'Banner/Image'), ('script', 'Script/Code'), ('yt_link', 'Youtube Embeded Link')], max_length=20)),
                ('ad_input_url', models.URLField(blank=True, null=True)),
                ('ad_input_image', models.ImageField(upload_to='ads/image_ads')),
                ('ad_input_script', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='adView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateField(auto_now_add=True)),
                ('earned_amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('AD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.ad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earned', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('today_earned', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('last_updated', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
