# Generated by Django 5.2.6 on 2025-10-09 12:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_rename_ad_adview_ad_alter_ad_ad_input_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userearning',
            name='today_earned',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='userearning',
            name='total_earned',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
