# Generated by Django 5.2.6 on 2025-10-09 12:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_userearning_today_earned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userearning',
            name='today_earned',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='userearning',
            name='total_earned',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12),
        ),
    ]
