# Generated by Django 5.2.6 on 2025-10-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_userearning_today_earned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_ad_show',
            field=models.BooleanField(default=True),
        ),
    ]
