# Generated by Django 5.2.6 on 2025-10-16 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_ad_is_ad_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='is_ad_show',
        ),
    ]
